PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX rss-assess: <https://w3id.org/railsec-scope/assessment#>
PREFIX rss-core: <https://w3id.org/railsec-scope/core#>
PREFIX rss-crit: <https://w3id.org/railsec-scope/criteria#>
PREFIX rss-res: <https://w3id.org/railsec-scope/results#>
PREFIX rsso: <https://w3id.org/railsec-scope/ontology#>

SELECT ?selection ?element ?difference WHERE { { ?selection a rss-res:Selection; rss-res:selectionBasedOnCandidateSet/rss-res:hasCandidateAssignment/rss-res:materialisesEvaluation/rss-res:evaluationConcernsElement ?element . FILTER NOT EXISTS { ?selection rss-res:includesElement ?element } BIND("candidate-not-selected" AS ?difference) } UNION { ?selection rss-res:includesElement ?element . FILTER NOT EXISTS { ?selection rss-res:selectionBasedOnCandidateSet/rss-res:hasCandidateAssignment/rss-res:materialisesEvaluation/rss-res:evaluationConcernsElement ?element } BIND("selected-not-candidate" AS ?difference) } }
