PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rss-crit: <https://w3id.org/railsec-scope/criteria#>
PREFIX rss-rail: <https://w3id.org/railsec-scope/railway#>
PREFIX rss-res: <https://w3id.org/railsec-scope/results#>

CONSTRUCT { ?flow rdf:type ?category . }
WHERE {
  ?evaluation a rss-res:CriterionEvaluation ;
      rss-res:evaluationConcernsElement ?flow ;
      rss-res:evaluatesCriterion ?criterion ;
      rss-res:hasEvaluationOutcome rss-res:satisfied .
  ?criterion rss-crit:determinesMembershipOf ?category .
  VALUES ?category { rss-rail:Category1Transmission rss-rail:Category2Transmission rss-rail:Category3Transmission }
  FILTER(isIRI(?evaluation) && isIRI(?flow) && isIRI(?criterion) && isIRI(?category))
}
